name: Destiny
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Is the destiny a choice?
      run: |
            npm install xhr2
            node imitation.js > README.md
    - name: Check if there are any changes
      id: verify_diff
      run: |
        git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
    - name: Commit change & Push
      if: steps.verify_diff.outputs.changed == 'true'
      run: |
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -am "Choice has been made."
            git push
