name: Destiny
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Is the destiny a choice?
      run: node imitation.js > README.md
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: steps.auto-commit-action.outputs.changes_detected == 'true'
      with:
        commit_message: Choice has been made.
      
